"""Validation utilities (purged walk-forward, metrics, conformal)."""

from src.validation.metrics import (
    calmar_ratio,
    periodic_sharpe,
    probabilistic_sharpe_ratio,
    probability_backtest_overfitting,
)
from src.validation.trials import (
    CLAIM_GROSS_EDGE,
    CLAIM_MECHANICS_CLEAN,
    CLAIM_NET_EDGE,
    CLAIM_NO_CLAIM,
    CLAIM_ROBUST_EDGE,
    CLAIM_TIERS,
    REQUIRED_PACKET_KEYS,
    TRIAL_PACKET_SCHEMA_VERSION,
    ResearchClaimPacket,
    build_research_claim_packet,
    classify_claim_tier,
    compute_trial_metrics,
    current_git_commit,
    emit_research_claim_packet,
    stable_config_hash,
    summary_claim_fields,
    validate_claim_packet_dir,
    write_research_claim_packet,
)
from src.validation.walk_forward import PurgedWalkForward

__all__ = [
    "PurgedWalkForward",
    "CLAIM_GROSS_EDGE",
    "CLAIM_MECHANICS_CLEAN",
    "CLAIM_NET_EDGE",
    "CLAIM_NO_CLAIM",
    "CLAIM_ROBUST_EDGE",
    "CLAIM_TIERS",
    "REQUIRED_PACKET_KEYS",
    "ResearchClaimPacket",
    "TRIAL_PACKET_SCHEMA_VERSION",
    "build_research_claim_packet",
    "calmar_ratio",
    "classify_claim_tier",
    "compute_trial_metrics",
    "current_git_commit",
    "emit_research_claim_packet",
    "periodic_sharpe",
    "probabilistic_sharpe_ratio",
    "probability_backtest_overfitting",
    "stable_config_hash",
    "summary_claim_fields",
    "validate_claim_packet_dir",
    "write_research_claim_packet",
]
